# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d649862e18c6dea4081ce2a730112474879f695e8f4b296c0113e0c55ebb8cb690d56d1feab1b3b19b807e82dd29eb5061c9cc5904ef787c988e1af00fa3c6a8

test:
  secret_key_base: 943349b4d683a983b685470cee533bfa34df467501ae057688d1202faf3ced411e72dab766dfa02d5baa9145c95972d8fe17ce11e5e7bff29c646b618bc89b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
