# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: poll_app
  host: localhost
  username: appacademy
